variables:
  initiativeDefRootFolder: '"$(System.DefaultWorkingDirectory)/"'
  # folder 
  folderName: "Initiatives" 
  # managementGroupID where azure policy definitions are stored, best practice is Tentant Root Group
  managementGroupID: "INPUT MGMT GROUP ID"
  # service connections specific to each deployment environment
  devServiceConnection: "INPUT SERVICE CONNECTION"
  nonprodServiceConnection: "INPUT SERVICE CONNECTION"
  prodServiceConnection: "INPUT SERVICE CONNECTION"
  Initiatives: ""
  
trigger:
  branches:
    # branch names are case senititve
    include:
    - main
  paths:
    # triggers only on modification to contents of initiative directory
    include:
    - Initiatives/*
    exclude:
    - Inititaives/README.MD

stages:
  - stage: DEV
    displayName: "DEV"
    jobs:
      - deployment: DEV_Deployment
        environment: SCaC-DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: PowerShell@2
                  displayName: "Check file diff"
                  inputs:
                    filePath: "Libraries/Tools/Misc/checkDiff.ps1"
                    arguments: "-folderName $(folderName)
                      -defRootFolder $(initiativeDefRootFolder)"

                - task: AzurePowerShell@4
                  displayName: "Create Initiative Definition"
                  inputs:
                    azureSubscription: $(devServiceConnection)
                    ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
                    ScriptArguments: '-rootFolder $(initiativeDefRootFolder)
                          -modifiedInitiatives $(Initiatives)
                          -managementGroupName $(managementGroupID)'
                    azurePowerShellVersion: LatestVersion
                  condition: and(succeeded(), ne(variables['Initiatives'], ''))

  - stage: QA
    displayName: "QA"
    condition: contains(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - deployment: QA_Deployment
        environment: SCaC-QA
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: PowerShell@2
                  displayName: "Check file diff"
                  condition: ne(variables['Build.Reason'], 'Manual')
                  inputs:
                    filePath: "Libraries/Tools/Misc/checkDiff.ps1"
                    arguments: "-folderName $(folderName)
                      -defRootFolder $(initiativeDefRootFolder)"

                - task: AzurePowerShell@4
                  displayName: "Create Initiative Definition"
                  inputs:
                    azureSubscription: $(nonprodServiceConnection)
                    ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
                    ScriptArguments: '-rootFolder $(initiativeDefRootFolder)
                          -modifiedInitiatives $(Initiatives)
                          -managementGroupName $(managementGroupID)'
                    azurePowerShellVersion: LatestVersion
                  condition: and(succeeded(), ne(variables['Initiatives'], ''))

  - stage: PROD
    displayName: "PROD"
    condition: contains(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - deployment: PROD_Deployment
        environment: SCaC-PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: PowerShell@2
                  displayName: "Check file diff"
                  condition: ne(variables['Build.Reason'], 'Manual')
                  inputs:
                    filePath: "Libraries/Tools/Misc/checkDiff.ps1"
                    arguments: "-folderName $(folderName)
                      -defRootFolder $(initiativeDefRootFolder)"

                - task: AzurePowerShell@4
                  displayName: "Create Initiative Definition"
                  inputs:
                    azureSubscription: $(prodServiceConnection)
                    ScriptPath: 'Libraries/Tools/Az/Create-InitiativeDef.ps1'
                    ScriptArguments: '-rootFolder $(initiativeDefRootFolder)
                          -modifiedInitiatives $(Initiatives)
                          -managementGroupName $(managementGroupID)'
                    azurePowerShellVersion: LatestVersion
                  condition: and(succeeded(), ne(variables['Initiatives'], ''))
